#ifndef _MPEG2_GUIAPI_MSG_H_
#define _MPEG2_GUIAPI_MSG_H_

#define WM_TSMAGIC_OFFLINE_THREAD				WM_USER + 1000
#define WM_TSMAGIC_REALTIME_THREAD				WM_USER + 1001
#define WM_TSMAGIC_DOWNLOAD_THREAD				WM_USER + 1002
#define WM_TSMAGIC_DECIMATE_THREAD				WM_USER + 1003
#define WM_TSMAGIC_RECORD_THREAD				WM_USER + 1004

#define WM_TSMAGIC_APPEND_LOG					WM_USER + 1100

#define WM_TSMAGIC_REPORT_RATIO					WM_USER + 1101
#define WM_TSMAGIC_REPORT_FILESIZE				WM_USER + 1102

#define WM_TSMAGIC_DOWNLOAD_LOG					WM_USER + 1103
#define WM_TSMAGIC_DOWNLOAD_RATIO				WM_USER + 1104

#define WM_TSMAGIC_DECIMATE_LOG					WM_USER + 1105
#define WM_TSMAGIC_DECIMATE_RATIO				WM_USER + 1106

#define WM_TSMAGIC_RECORD_LOG					WM_USER + 1107
#define WM_TSMAGIC_RECORD_RATIO					WM_USER + 1108

#define WM_TSMAGIC_ETR290_LOG					WM_USER + 1110

#define WM_TSMAGIC_REPORT_BITRATE				WM_USER + 1111
#define WM_TSMAGIC_REPORT_BITRATE_MAP			WM_USER + 1112
#define WM_TSMAGIC_REPORT_PACKET_LENGTH			WM_USER + 1113

#define WM_TSMAGIC_TS_TRIGGER_STATE				WM_USER + 1115
#define WM_TSMAGIC_PES_TRIGGER_STATE			WM_USER + 1116
#define WM_TSMAGIC_ES_TRIGGER_STATE				WM_USER + 1117
#define WM_TSMAGIC_SECTION_TRIGGER_STATE		WM_USER + 1118

#define WM_TSMAGIC_REPORT_SIGNAL_STATUS			WM_USER + 1120

#define WM_ESDEMUXTHREAD_EXIT					WM_USER + 1200

#define WM_UPDATE_PAT						WM_USER + 2000
#define WM_UPDATE_PMT						WM_USER + 2001
#define WM_UPDATE_CAT						WM_USER + 2002
#define WM_UPDATE_BAT						WM_USER + 2003
#define WM_UPDATE_NIT						WM_USER + 2004
#define WM_UPDATE_SDT						WM_USER + 2005
#define WM_UPDATE_EIT						WM_USER + 2006
#define WM_UPDATE_RST						WM_USER + 2007
#define WM_UPDATE_TDT						WM_USER + 2008
#define WM_UPDATE_TOT						WM_USER + 2009

#define WM_UPDATE_TS_PACKET_STATISTIC			WM_USER + 2020

#define WM_UPDATE_TRIGGER_TS_PACKET				WM_USER + 2030
#define WM_UPDATE_TRIGGER_TS_PID				WM_USER + 2031
#define WM_UPDATE_TRIGGER_PSISI_SECTION			WM_USER + 2032

#define WM_UPDATE_PCR_STATISTIC					WM_USER + 2040
#define WM_UPDATE_EPG_INFO						WM_USER + 2045

//#define WM_UPDATE_PES_HEADER									WM_USER + 2050
//
//#define WM_UPDATE_M2A_ES_HEADER									WM_USER + 2061
//#define WM_UPDATE_M2A_ES_ERROR_CHECK							WM_USER + 2062
//#define WM_UPDATE_M2A_ES_AUDIO_DATA								WM_USER + 2063
//
//#define WM_UPDATE_AC3_ES_SYNCINFO								WM_USER + 2071
//#define WM_UPDATE_AC3_ES_BSI									WM_USER + 2072
//#define WM_UPDATE_AC3_ES_AUDBLK									WM_USER + 2073
//#define WM_UPDATE_AC3_ES_AUXDATA								WM_USER + 2074
//#define WM_UPDATE_AC3_ES_ERRORCHECK								WM_USER + 2075

//#define WM_UPDATE_M2V_ES_SEQUENCE_HEADER						WM_USER + 2081
//#define WM_UPDATE_M2V_ES_SEQUENCE_EXTENSION						WM_USER + 2082
//#define WM_UPDATE_M2V_ES_SEQUENCE_DISPLAY_EXTENSION				WM_USER + 2083
//#define WM_UPDATE_M2V_ES_SEQUENCE_SCALABLE_EXTENSION			WM_USER + 2084
//#define WM_UPDATE_M2V_ES_QUANT_MATRIX_EXTENSION					WM_USER + 2085
//#define WM_UPDATE_M2V_ES_GROUP_OF_PICTURES_HEADER				WM_USER + 2086
//#define WM_UPDATE_M2V_ES_PICTURE_HEADER							WM_USER + 2087
//#define WM_UPDATE_M2V_ES_PICTURE_CODING_EXTENSION				WM_USER + 2088
//#define WM_UPDATE_M2V_ES_PICTURE_DISPLAY_EXTENSION				WM_USER + 2089
//#define WM_UPDATE_M2V_ES_PICTURE_TEMPORAL_SCALABLE_EXTENSION	WM_USER + 2090
//#define WM_UPDATE_M2V_ES_PICTURE_SPATIAL_SCALABLE_EXTENSION		WM_USER + 2091
//#define WM_UPDATE_M2V_ES_COPYRIGHT_EXTENSION					WM_USER + 2092
//#define WM_UPDATE_M2V_ES_SLICE									WM_USER + 2093
//#define WM_UPDATE_M2V_ES_GOP_TIME								WM_USER + 2094
//#define WM_UPDATE_M2V_ES_SEQUENCE_END							WM_USER + 2095
//#define WM_UPDATE_M2V_ES_UNKNOWN_NAL							WM_USER + 2096

//#define WM_UPDATE_MPEG_PACK_HEADER									WM_USER + 2100
//#define WM_UPDATE_MPEG_SYSTEM_HEADER								WM_USER + 2101
//
//#define WM_UPDATE_H264_ES_SEQ_PARAMETER_SET							WM_USER + 2281
//#define WM_UPDATE_H264_ES_PIC_PARAMETER_SET							WM_USER + 2282
//#define WM_UPDATE_H264_ES_SLICE_OF_AN_IRD_PICTURE					WM_USER + 2283
//#define WM_UPDATE_H264_ES_SLICE_OF_A_NON_IDR_PICTURE				WM_USER + 2284
//
//#define WM_UPDATE_H264_PACK_HEADER									WM_USER + 2300
//#define WM_UPDATE_H264_SYSTEM_HEADER								WM_USER + 2301
//
//#define WM_UPDATE_AAC_ES_HEADER										WM_USER + 2311
//
//#define WM_UPDATE_AVS_ES_SEQUENCE_HEADER							WM_USER + 2401
//#define WM_UPDATE_AVS_ES_SEQUENCE_END								WM_USER + 2402
//#define WM_UPDATE_AVS_ES_I_PICTURE_HEADER							WM_USER + 2403
//#define WM_UPDATE_AVS_ES_PB_PICTURE_HEADER							WM_USER + 2404
//#define WM_UPDATE_AVS_ES_SEQUENCE_DISPLAY_EXTENSION					WM_USER + 2405
//#define WM_UPDATE_AVS_ES_PICTURE_DISPLAY_EXTENSION					WM_USER + 2406
//#define WM_UPDATE_AVS_ES_CAMERA_PARAMETERS_EXTENSION				WM_USER + 2407
//#define WM_UPDATE_AVS_ES_COPYRIGHT_EXTENSION						WM_USER + 2408
//#define WM_UPDATE_AVS_ES_USER_DATA									WM_USER + 2409
//
//#define WM_UPDATE_AVS_VIDEO_ES_TIMECODE								WM_USER + 2410
//
#define WM_UPDATE_WAVE_HEADER										WM_USER + 2421
//#define WM_REPORT_VIDEO_DECODE_FPS										WM_USER	+ 2500

#endif		//_MPEG2_GUIAPI_MSG_H_
