#ifndef _DEFINE_H_
#define _DEFINE_H_

#define CHINESE_VERSION					1
#define OFFLINE_ANALYZE					0

#define TS_FILE_READ_INTEGRITY_DIAGNOSIS	0

#define REPORT_FILE_ANALYSE_RATIO		1

#define OPEN_TS_PACKET_ANALYZER			1
#define OPEN_PACKET_STATISTIC			1
#define OPEN_PCR_ANALYZER				1

#define OPEN_SECTION_SPLICER			1
#define OPEN_SECTION_TRIGGER			1
#define OPEN_TS_PACKET_TRIGGER			1
#define OPEN_PES_PACKET_TRIGGER			1

#define OPEN_AC3_AUDIO_ANALYZER			1
#define OPEN_MPEG_AUDIO_ANALYZER		1
#define OPEN_MPEG_VIDEO_ANALYZER		1
#define OPEN_H264_VIDEO_ANALYZER		1
#define OPEN_AVS_VIDEO_ANALYZER			1
#define OPEN_AAC_AUDIO_ANALYZER			1
#define OPEN_MPEG_PS_ANALYZER			1
#define OPEN_YUV_VIDEO_ANALYZER			1
/*------------------------------------------------------------
					GUI interface definition
-------------------------------------------------------------*/
#define BYTE_BUFFER_USE_LISTCTRL_VIEW				0

/*------------------------------------------------------------
					Message definition
-------------------------------------------------------------*/
#define MAX_TXT_CHARS						256
#define MAX_LOG_COUNT						4096

typedef enum _FILTER_PSISI_SYNTAX
{
	FILTER_PSISI_ANALYZER		= 0,
	FILTER_PSISI_SYNTAX_PAT,
	FILTER_PSISI_SYNTAX_PMT,
	FILTER_PSISI_SYNTAX_CAT,
	FILTER_PSISI_SYNTAX_TSDT,
	FILTER_PSISI_SYNTAX_NIT,
	FILTER_PSISI_SYNTAX_SDT,
	FILTER_PSISI_SYNTAX_EIT,
	FILTER_PSISI_SYNTAX_BAT,
	FILTER_PSISI_SYNTAX_TDT,
	FILTER_PSISI_SYNTAX_TOT,
	FILTER_PSISI_SYNTAX_RST,
	FILTER_PSISI_SYNTAX_AIT,
	FILTER_PSISI_SYNTAX_INT,
	FILTER_PSISI_SYNTAX_MPE,
	FILTER_PSISI_SYNTAX_DSMCC,
} FILTER_PSISI_SYNTAX_e;

typedef enum _DEBUG_STAGE
{
	DEBUG_OPEN			= 0,
	DEBUG_INFO,
	DEBUG_WARNING,
	DEBUG_ERROR,
	DEBUG_IDLE,
	DEBUG_SAVE,
	DEBUG_CLOSE
} DEBUG_TYPE_e;

#endif
