#ifndef _GUIAPI_MSG_H_
#define _GUIAPI_MSG_H_

#define WM_APPEND_LOG					WM_USER + 0x4e76
#define WM_PLAY_THREAD_EXIT				WM_USER + 0x81D8
#define WM_PLAY_WORKING_PROGRESS		WM_USER + 0x53d4


#endif		//_GUIAPI_MSG_H_
