//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 EverStationII.rc 使用
//
#define IDC_BTN_BROWSE_VFILE            3
#define IDC_BTN_PCAP_                   3
#define IDC_BTN_PCAP_DIAGNOSE           3
#define IDC_BTN_BROWSE_AFILE            4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ANALYSE_PROGRESS            101
#define IDD_FORMVIEW                    101
#define IDD_FORMVIEW_EPG_CONTAINER      101
#define IDS_ANALYSE_OBJECT              102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDD_TS_ANALYZER_PACKET_TRIGGER  122
#define IDS_STATUS_PANE2                123
#define IDD_TS_SECTION_TRIGGER          123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDD_TS_ANALYZER_PACKETS         126
#define IDR_TSMAGIC                     127
#define IDR_MAINFRAME                   128
#define IDD_TS_ANALYZER_BOUQUETS        128
#define IDR_MAINFRAME_256               129
#define IDR_YUVMAGIC                    129
#define IDR_EverStationIITYPE           130
#define IDD_TS_ANALYZER_EPG             130
#define ID_WINDOW_MANAGER               131
#define IDD_TS_ANALYZER_OVERVIEW        132
#define IDR_ESMAGIC                     132
#define IDR_RIGHT_KEY_MENU              132
#define ID_VIEW_FILEVIEW                133
#define IDD_TS_ANALYZER_SERVICES        133
#define IDR_PSMAGIC                     133
#define ID_VIEW_CLASSVIEW               134
#define IDD_TS_ANALYZER_PCR             134
#define ID_PROPERTIES                   135
#define IDD_TS_ANALYZER_PESES           135
#define ID_OPEN                         136
#define IDD_TS_PACKET_MODIFY            136
#define ID_OPEN_WITH                    137
#define IDD_MAGIC_TS                    137
#define ID_DUMMY_COMPILE                138
#define IDD_MAGIC_YUV                   138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define IDD_YUV_PREVIEW                 139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define IDD_SIGNAL_STATUS               140
#define ID_CLASS_DEFINITION             141
#define IDD_TS_ANALYZER_PSISI           141
#define ID_CLASS_PROPERTIES             142
#define IDD_MAGIC_ES                    142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define IDD_MAGIC_PS                    145
#define ID_SORTING_SORTALPHABETIC       146
#define IDD_PS_OVERVIEW                 146
#define ID_SORTING_SORTBYTYPE           147
#define IDD_ES_OVERVIEW                 147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_RUNNINGLOGWND           149
#define IDD_TS_ETR290                   149
#define ID_VIEW_PROPERTIESWND           150
#define IDD_TS_DTS_PTS                  150
#define ID_SORTPROPERTIES               151
#define IDD_DECIMATE                    151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define IDD_REGISTER                    153
#define ID_EXPAND_ALL                   154
#define IDD_TS_ANALYZER_NETWORK         154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_RUNNING_LOG_WND             157
#define IDS_PROPERTIES_WND              158
#define IDB_ES                          159
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_TOOLBAR_FRAME               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDB_CONSOLE                     173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDD_TRIGGER_WAITING             181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDD_SHOW_VIDEO                  184
#define IDD_YUV_COMBINE                 185
#define IDD_DYUV_FILE                   186
#define IDD_ANALYSE_PROGRESS            187
#define IDD_TS_ANALYZER_OCDC            188
#define IDD_TS_ANALYZER_TELETEXT        189
#define IDD_TS_ANALYZER_SUBTITLE        190
#define IDD_TS_ANALYZER_ES              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDB_LOG                         268
#define IDS_USER_ACTION_TAB             300
#define IDS_TS_WARNING_TAB              301
#define IDS_PCR_RECORD_TAB              302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_TOOLBAR_FRAME_256           311
#define IDD_CONFIG_SYSDEBUG             313
#define IDD_CONFIG_WINPCAP              314
#define IDD_CONFIG_TSINPUT              317
#define IDD_TS_ANALYZER_NORMAL          318
#define IDD_TS_ANALYZER_EPG1            319
#define IDD_TS_ANALYZER_DSMCC           319
#define IDB_BITMAP_TREESTATE            384
#define IDC_BTN_TSMAGIC                 1000
#define IDC_STATIC_APPNAME              1000
#define IDC_STATIC_APPNAME_EVERSTATIONII 1000
#define IDC_RADIO_TSIN_DEKTEC           1001
#define IDC_RADIO_TSIN_SMARTTS          1002
#define IDC_TAB_TSMAGIC                 1003
#define IDC_RADIO_TSIN_FILE_SIMULATE    1003
#define IDC_PROGRESS_FILERATIO          1004
#define IDC_RADIO_TSIN_UDP              1004
#define IDC_LIST_SECTION_DATA           1005
#define IDC_BTN_FILE_BROWSE             1005
#define IDC_BTN_OPEN                    1006
#define IDC_EDIT_TS_FILE                1006
#define IDC_IPADDRESS1                  1007
#define IDC_IPADDRESS_TS_INPUT          1007
#define IDC_BTN_PREVIEW                 1008
#define IDC_EDIT_TS_UDP_PORT            1008
#define IDC_CHECK_ENABLE_PCR_DEBUG      1008
#define IDC_CHECK_ENABLE_TSRATE_DEBUG   1009
#define IDC_BTN_ESMAGIC                 1010
#define IDC_EDIT_PCAP_FILTER            1010
#define IDC_BTN_ES2TS                   1011
#define IDC_LIST_PCAP_DEVICES           1011
#define IDC_STATIC_MONITORS             1012
#define IDC_EDT_TSPACKET_TRIGGER_COUNT  1013
#define IDC_BTN_STREAM                  1015
#define IDC_BTN_DISPATCH                1015
#define IDC_BTN_PS_PREVIEW              1016
#define IDC_TAB_YUVMAGIC                1017
#define IDC_BTN_PS2TS                   1018
#define IDC_EDIT_FILE                   1019
#define IDC_SPIN_TSPACKET_TRIGGER_COUNT 1020
#define IDC_LIST_PID                    1021
#define IDC_CMB_TSPACKET_PID            1022
#define IDC_EDIT_YUV                    1025
#define IDC_SLIDER_FILE                 1026
#define IDC_CMB_TSPACKET_TRANSPORT_SCRAMBLING_CONTROL 1027
#define IDC_EDIT_START                  1028
#define IDC_CMB_TSPACKET_ADAPTATION_FIELD_CONTROL 1029
#define IDC_EDIT_END                    1030
#define IDC_CMB_TSPACKET_CONTINUITY_COUNTER 1031
#define IDC_EDIT_LENGTH                 1032
#define IDC_BTN_DECIMATE_TS2ES          1033
#define IDC_BTN_DECIMATE_TS2TS          1034
#define IDC_CMB_TSPACKET_TRANSPORT_ERROR_INDICATOR 1034
#define IDC_STATIC_START                1035
#define IDC_BTN_DECIMATE_TS2PES         1036
#define IDC_CMB_TSPACKET_PAYLOAD_UNIT_START_INDICATOR 1036
#define IDC_BTN_DECIMATE_STOP           1037
#define IDC_CMB_ES_TYPE                 1037
#define IDC_STATIC_END                  1038
#define IDC_CMB_TSPACKET_TRANSPORT_PRIORITY 1039
#define IDC_STATIC_LENGTH               1040
#define IDC_STATIC_FORMAT               1041
#define IDC_CMB_TSPACKET_PCR_FLAG       1042
#define IDC_STATIC_VID_JITTER_GRAPH     1043
#define IDC_STATIC_VID_INTERVAL_GRAPH   1044
#define IDC_STATIC_VID_JITTER           1046
#define IDC_STATIC_VID_INTERVAL         1047
#define IDC_STATIC_INFO_FPS             1047
#define IDC_BTN_LEFTMARK                1048
#define IDC_LIST_PROGRESS_LOG           1048
#define IDC_STATIC_TITLE                1049
#define IDC_CMB_DISPATCH_OPTION         1049
#define IDC_LIST_ES_INFO                1050
#define IDC_STATIC_AUD_JITTER_GRAPH     1051
#define IDC_LIST_TS_MONITOR             1052
#define IDC_TREE_PS_SYNTAX              1052
#define IDC_STATIC_AUD_INTERVAL_GRAPH   1053
#define IDC_LIST_TS_OVERVIEW            1053
#define IDC_STATIC_TSRATE               1054
#define IDC_LIST_PCR_LOG                1055
#define IDC_LIST_TS_BANDWIDTH           1055
#define IDC_EDIT_VFILE                  1055
#define IDC_STATIC_AUD_JITTER           1056
#define IDC_EDIT_USERID                 1056
#define IDC_EDIT_AFILE                  1056
#define IDC_STATIC_AUD_INTERVAL         1057
#define IDC_TREE_OCDC_SYNTAX            1059
#define IDC_BTN_STOP                    1059
#define IDC_EDIT_TOTAL                  1060
#define IDC_LIST_OCDC_SERVICES          1061
#define IDC_STATIC_TOTAL                1062
#define IDC_LIST_TELETEXT_PID           1065
#define IDC_EDIT_TELETEXT_CUR_PID       1066
#define IDC_BTN_TELETEXT_TRIGGER        1067
#define IDC_TREE_TELETEXT_SYNTAX        1068
#define IDC_LIST_SUBTITLE_PID           1069
#define IDC_EDIT_SUBTITLE_CUR_PID       1070
#define IDC_BTN_SUBTITLE_TRIGGER        1071
#define IDC_TREE_SUBTITLE_SYNTAX        1072
#define IDC_STATIC_TS_RESULT            1073
#define IDC_STATIC_TS_CONDITION         1074
#define IDC_STATIC_TRIGGER_MASK         1076
#define IDC_STATIC_TRIGGER_DATA         1077
#define IDC_TREE_TS_PROGRAMS            1078
#define IDC_STATIC_ES_VIDEO             1079
#define IDC_STATIC_ES_AUDIO             1080
#define IDC_BTN_TSPACKET_RESET          1092
#define IDC_BTN_NEXT_FRAME              1100
#define IDC_BTN_NEXT_5FRAME             1101
#define IDC_BTN_LAST_FRAME              1102
#define IDC_BTN_SAVE_BMP                1103
#define IDC_BTN_GRID                    1104
#define IDC_BTN_INFO                    1105
#define IDC_BTN_FIRST_FRAME             1106
#define IDC_BTN_PRE_5FRAME              1107
#define IDC_BTN_PRE_FRAME               1108
#define IDC_BTN_PLAY                    1109
#define IDC_BTN_ES_WATCH                1111
#define IDC_BTN_ES_TRIGGER              1112
#define IDC_EDIT_ES_GOP_TIME            1113
#define IDC_STATIC_ES_GOP_TIME          1114
#define IDC_EDIT_ES_VIDEO               1115
#define IDC_BTN_ES_PTS                  1116
#define IDC_EDIT_ES_AUDIO               1117
#define IDC_BTN_ES_DTS                  1118
#define IDC_BTN_ES_BUFFER               1119
#define IDC_BTN_RIGHTMARK               1120
#define IDC_LIST_SRC                    1123
#define IDC_BTN_UP                      1126
#define IDC_BTN_DOWN                    1127
#define IDC_EDIT1                       1128
#define IDC_BTN_ADD                     1129
#define IDC_EDIT2                       1130
#define IDC_BTN_DEL                     1131
#define IDC_LIST1                       1134
#define IDC_EDIT_DST_FILE               1135
#define IDC_LIST_PCAP_DEBUG_LOG         1135
#define IDC_BUTTON1                     1136
#define IDC_BTN_TSPACKET_SEARCH         1137
#define IDC_BTN_SAVEAS_YUV              1138
#define IDC_BUTTON2                     1139
#define IDC_BTN_SECTION_PRE             1140
#define IDC_EDIT_PRE_FILENAME           1141
#define IDC_BTN_COMBINE                 1142
#define IDC_BUTTON3                     1143
#define IDC_BTN_LOOKUP                  1144
#define IDC_BUTTON4                     1145
#define IDC_EDIT_NUM_WIDTH              1146
#define IDC_RDO_DYDUDV2YUV              1147
#define IDC_EDIT_NUM_START              1148
#define IDC_RDO_DYUV2YUV                1149
#define IDC_CMB_WH                      1150
#define IDC_SLIDER_TS_PACKET            1151
#define IDC_EDIT_NUM_END                1152
#define IDC_CMB_FRAMERATE               1153
#define IDC_CMB_FOURCC                  1154
#define IDC_CHECK_CYCLE                 1154
#define IDC_CMB_DISPLAY                 1157
#define IDC_CMB_COMPONENT               1158
#define IDC_BTN_RESET                   1159
#define IDC_CMB_FILEFORMAT              1160
#define IDC_BTN_TSPACKET_CLEAR          1161
#define IDC_TREE_ES_SYNTAX              1161
#define IDC_BTN_TSPACKET_PRE            1162
#define IDC_BTN_SECTION_NEXT            1163
#define IDC_BTN_TSPACKET_NEXT           1164
#define IDC_CHECK3                      1256
#define IDC_CHECK4                      1257
#define IDC_CHECK5                      1258
#define IDC_CHECK6                      1259
#define IDC_CHECK7                      1260
#define IDC_CHECK8                      1261
#define IDC_CHECK9                      1262
#define IDC_CHECK10                     1263
#define IDC_CHECK11                     1264
#define IDC_CHECK12                     1265
#define IDC_CHECK13                     1266
#define IDC_CHECK17                     1270
#define IDC_COMBO_SECTION_PID           1275
#define IDC_LIST_DATA_MASK              1276
#define IDC_SLIDER_SECTION              1277
#define IDC_BTN_SECTION_SEARCH          1278
#define IDC_BTN_SECTION_CLEAR           1279
#define IDC_BTN_SECTION_RESET           1280
#define IDC_PROGRESS_WAITING            1282
#define IDC_STATIC_MASK                 1283
#define IDC_LED_SYNCLOSE                1284
#define IDC_STATIC_DATA                 1284
#define IDC_LED_SYNCBYTE                1285
#define IDC_LED_PAT                     1286
#define IDC_LED_CC                      1287
#define IDC_LED_PMT                     1288
#define IDC_LED_PID                     1289
#define IDC_CHECK1                      1290
#define IDC_CHECK2                      1291
#define IDC_CHECK14                     1292
#define IDC_CHECK15                     1293
#define IDC_CHECK16                     1294
#define IDC_CHECK18                     1295
#define IDB_TREELIST_BITMAP             8000
#define IDB_TREELIST_CHECK              8003
#define IDB_TREELIST_LOCK               8004
#define IDB_TREELIST_TREE               8008
#define IDB_TREELIST_SORT               8009
#define IDB_TREELIST_HEADER             8010
#define IDB_TREELIST_DISABLE            8011
#define IDB_TREE_INFO                   8012
#define IDB_EPG                         8013
#define IDB_BOUQUET                     8014
#define IDB_MENU_IMAGES_25              8015
#define IDB_TOOLBAR_IMAGES_24           8015
#define ID_MENU_SETUP_SYS_DEBUG         32773
#define ID_MENU_SETUP_WINPCAP_DEBUG     32774
#define ID_MENU_SETUP_TS_INPUT          32776
#define ID_ES_VIDEO_PREVIEW             32780
#define ID_ES_AUDIO_PREVIEW             32781
#define ID_OCDC_DOWNLOAD                32782
#define ID_TS_DECIMATE                  32783
#define ID_TS_DECIMATE_TO_TS            32784
#define ID_TS_DECIMATE_TO_ES            32786
#define ID_ES_SYNTAX_ANALYSE            32787
#define ID_TS_DECIMATE_TO_PES           32788
#define ID_TS_DECIMATE_TO_SECTION       32789
#define ID_ES32790                      32790
#define ID_ES32791                      32791
#define ID_ES_PTS_ANALYSE               32792
#define ID_ES_DTS_ANALYSE               32793
#define ID_ES32794                      32794
#define ID_ES_BUF_ANALYSE               32795
#define IDC_BTN_YUVMAGIC                32845
#define IDC_BTN_PSMAGIC                 32849

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           320
#endif
#endif
