#ifndef _MPEG2_STREAM_TYPE_H_
#define _MPEG2_STREAM_TYPE_H_

#include <stdint.h>

#include "../compile.h"

typedef enum
{
	STREAM_SUBTYPE_UNKNOWN = 0,
	STREAM_SUBTYPE_AIT = 1,
	STREAM_SUBTYPE_INT = 2,
	STREAM_SUBTYPE_TELETEXT = 32,
	STREAM_SUBTYPE_SUBTITLE = 33,
	STREAM_SUBTYPE_AC3 = 34,
	STREAM_SUBTYPE_DRA = 35,
} STREAM_SUBTYPE_e;



#endif
