#ifndef __DVB_IPDC_DESCRIPTOR_H__
#define __DVB_IPDC_DESCRIPTOR_H__

/*descriptor tag define*/

//IPDC
#define DVB_IPDC_INT_TARGET_SMARTCARD_DESCRIPTOR						0x1006
#define DVB_IPDC_INT_TARGET_MAC_ADDRESS_DESCRIPTOR						0x1007
#define DVB_IPDC_INT_TARGET_SERIAL_NUMBER_DESCRIPTOR					0x1008
#define DVB_IPDC_INT_TARGET_IP_ADDRESS_DESCRIPTOR						0x1009
#define DVB_IPDC_INT_TARGET_IPV6_ADDRESS_DESCRIPTOR						0x100A
#define DVB_IPDC_INT_IPMAC_PLATFORM_NAME_DESCRIPTOR						0x100C
#define DVB_IPDC_INT_IPMAC_PLATFORM_PROVIDER_NAME_DESCRIPTOR			0x100D
#define DVB_IPDC_INT_TARGET_MAC_ADDRESS_RANGE_DESCRIPTOR				0x100E
#define DVB_IPDC_INT_TARGET_IP_SLASH_DESCRIPTOR							0x100F
#define DVB_IPDC_INT_TARGET_IP_SOURCE_SLASH_DESCRIPTOR					0x1010
#define DVB_IPDC_INT_TARGET_IPV6_SLASH_DESCRIPTOR						0x1011
#define DVB_IPDC_INT_TARGET_IPV6_SOURCE_SLASH_DESCRIPTOR				0x1012
#define DVB_IPDC_INT_IPMAC_STREAM_LOCATION_DESCRIPTOR					0x1013
#define DVB_IPDC_INT_ISP_ACCESS_MODE_DESCRIPTOR							0x1014


#endif